server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/aquasense/public;
    index index.html;
    server_name _;

    # Archivos estáticos
    location / {
        try_files $uri $uri/ =404;
    }

    # API PHP
    location /api/ {
        root /var/www/aquasense;
        try_files $uri =404;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        add_header Access-Control-Allow-Origin *;
    }

    access_log /var/log/nginx/aquasense_access.log;
    error_log  /var/log/nginx/aquasense_error.log;
}
